"""``hugin-init`` — scaffold ~/.config/hugin/ and an optional vault layout.

Idempotent: never overwrites existing files unless ``--force``. Run with no
flags for an interactive walkthrough; pass flags for non-interactive use.
"""

from __future__ import annotations

import argparse
import datetime as dt
import sys
from dataclasses import dataclass
from pathlib import Path

from hugin.config import ARCHIVE_DIRNAME_BY_LANGUAGE, config_dir


def _vault_subdirs(language: str) -> list[str]:
    archive = ARCHIVE_DIRNAME_BY_LANGUAGE.get(language, "archive")
    return [
        "journal",
        f"journal/{archive}",
        "meetings/transcripts",
        "meetings/summaries",
        "projects",
        "agenda_templates",
    ]

LANGUAGES = ("en", "sv")


@dataclass
class Answers:
    vault: Path
    language: str
    user_name: str
    scaffold_vault: bool


def _prompt(question: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    raw = input(f"{question}{suffix}: ").strip()
    return raw or default


def _prompt_choice(question: str, choices: tuple[str, ...], default: str) -> str:
    while True:
        raw = _prompt(f"{question} ({'/'.join(choices)})", default)
        if raw in choices:
            return raw
        print(f"  must be one of: {', '.join(choices)}", file=sys.stderr)


def _prompt_yes_no(question: str, default: bool = True) -> bool:
    suffix = "Y/n" if default else "y/N"
    while True:
        raw = input(f"{question} [{suffix}]: ").strip().lower()
        if not raw:
            return default
        if raw in ("y", "yes"):
            return True
        if raw in ("n", "no"):
            return False


def _gather_interactive(initial: Answers) -> Answers:
    print("Hugin setup — answer or press Enter for the default.\n")
    vault = Path(_prompt("Vault path", str(initial.vault))).expanduser()
    language = _prompt_choice("Language", LANGUAGES, initial.language)
    user_name = _prompt("Your name", initial.user_name)
    scaffold = _prompt_yes_no(f"Create vault subdirectories under {vault}?", initial.scaffold_vault)
    return Answers(vault=vault, language=language, user_name=user_name, scaffold_vault=scaffold)


def _render_hugin_yaml(answers: Answers) -> str:
    journal = answers.vault / "journal" / "journal.md"
    return (
        "# ~/.config/hugin/hugin.yaml  (shared across all hugin-* tools)\n"
        "# Generated by hugin-init. Tool-specific files (meetings.yaml,\n"
        "# agenda.yaml, ...) live next to this one and override these values.\n"
        "\n"
        f"language: {answers.language}\n"
        f'user_name: "{answers.user_name}"\n'
        f"vault_path: {answers.vault}\n"
        f"journal_path: {journal}\n"
        "\n"
        "# Google Workspace CLI used for calendar access. Install separately.\n"
        "gws_bin: gws\n"
        "# gws_config_dir: ~/.config/gws\n"
    )


def _render_journal(language: str) -> str:
    year = dt.date.today().year
    title = "Journal" if language == "en" else "Journal"
    return f"# {title} {year}\n"


@dataclass
class Action:
    path: Path
    kind: str  # "dir" | "file"
    status: str  # "create" | "skip-exists" | "overwrite"
    content: str | None = None


def _plan(answers: Answers, cfg_dir: Path, force: bool) -> list[Action]:
    actions: list[Action] = []

    actions.append(Action(cfg_dir, "dir", "create" if not cfg_dir.exists() else "skip-exists"))

    hugin_yaml = cfg_dir / "hugin.yaml"
    yaml_content = _render_hugin_yaml(answers)
    if hugin_yaml.exists() and not force:
        actions.append(Action(hugin_yaml, "file", "skip-exists", yaml_content))
    else:
        status = "overwrite" if hugin_yaml.exists() else "create"
        actions.append(Action(hugin_yaml, "file", status, yaml_content))

    if answers.scaffold_vault:
        for sub in [""] + _vault_subdirs(answers.language):
            target = answers.vault / sub if sub else answers.vault
            actions.append(
                Action(target, "dir", "create" if not target.exists() else "skip-exists")
            )

        journal_md = answers.vault / "journal" / "journal.md"
        journal_content = _render_journal(answers.language)
        if journal_md.exists() and not force:
            actions.append(Action(journal_md, "file", "skip-exists", journal_content))
        else:
            status = "overwrite" if journal_md.exists() else "create"
            actions.append(Action(journal_md, "file", status, journal_content))

    return actions


def _apply(actions: list[Action], dry_run: bool) -> None:
    for action in actions:
        marker = {"create": "+", "overwrite": "~", "skip-exists": "."}[action.status]
        suffix = "/" if action.kind == "dir" else ""
        print(f"  {marker} {action.path}{suffix}" + (" (skipped: exists)" if action.status == "skip-exists" else ""))
        if dry_run or action.status == "skip-exists":
            continue
        if action.kind == "dir":
            action.path.mkdir(parents=True, exist_ok=True)
        else:
            action.path.parent.mkdir(parents=True, exist_ok=True)
            action.path.write_text(action.content or "", encoding="utf-8")


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        prog="hugin-init",
        description="Scaffold ~/.config/hugin/ and an optional vault layout.",
    )
    p.add_argument("--vault", type=Path, help="Vault path (e.g. ~/Documents/notes)")
    p.add_argument("--language", choices=LANGUAGES, help="Default language for hugin-* tools")
    p.add_argument("--user-name", help="Your display name")
    p.add_argument("--no-vault", action="store_true", help="Skip creating vault subdirectories")
    p.add_argument("--config-dir", type=Path, help="Override the config dir (default ~/.config/hugin)")
    p.add_argument("--force", action="store_true", help="Overwrite existing files")
    p.add_argument("--dry-run", action="store_true", help="Show planned actions without writing")
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)

    defaults = Answers(
        vault=Path.home() / "Documents" / "notes",
        language="en",
        user_name="",
        scaffold_vault=True,
    )

    has_any_flag = any([args.vault, args.language, args.user_name, args.no_vault])
    if has_any_flag:
        answers = Answers(
            vault=(args.vault or defaults.vault).expanduser(),
            language=args.language or defaults.language,
            user_name=args.user_name or defaults.user_name,
            scaffold_vault=not args.no_vault,
        )
    else:
        answers = _gather_interactive(defaults)

    cfg_dir = (args.config_dir.expanduser() if args.config_dir else config_dir())

    print(f"\nConfig dir: {cfg_dir}")
    print(f"Vault:      {answers.vault}")
    print(f"Language:   {answers.language}")
    print(f"Name:       {answers.user_name or '(blank)'}")
    print(f"Scaffold:   {'yes' if answers.scaffold_vault else 'no'}")
    print()

    actions = _plan(answers, cfg_dir, args.force)
    _apply(actions, args.dry_run)

    if args.dry_run:
        print("\nDry run — nothing written.")
    else:
        print("\nDone. Edit ~/.config/hugin/hugin.yaml to tweak. Tools read it on next run.")
    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
